# VNPAY CONFIG M?I
vnpay.tmnCode=69Q2HQNA
vnpay.hashSecret=UM4C1WQLUZS01BNI9I4BBY3N40CPEH1K
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:8080/api/payment/vnpay-return